name        : xcb-util
version     : 0.4.0
release     : 7
source      :
    - http://xcb.freedesktop.org/dist/xcb-util-0.4.0.tar.gz : 0ed0934e2ef4ddff53fcc70fc64fb16fe766cd41ee00330312e20a985fd927a7
license     :
    - MIT
summary     : Additional extensions to the XCB library
component   : xorg.library
description : |
    The xcb-util package provides additional extensions to the XCB library, many that were previously found in Xlib, but are not part of core X protocol.
builddeps   :
    - pkgconfig32(xdmcp)
    - pkgconfig32(xcb)
    - pkgconfig32(xau)
emul32     : yes
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
