name       : xcb-util
version    : 0.4.0
release    : 8
source     :
    - http://xcb.freedesktop.org/dist/xcb-util-0.4.0.tar.gz : 0ed0934e2ef4ddff53fcc70fc64fb16fe766cd41ee00330312e20a985fd927a7
license    : MIT
component  : xorg.library
summary    : Additional extensions to the XCB library
description: |
    The xcb-util package provides additional extensions to the XCB library, many that were previously found in Xlib, but are not part of core X protocol.
emul32     : yes
builddeps  :
    - pkgconfig32(xcb)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
